# bin/audit.sh in sync with its 04g_security.sh generator heredoc (drift guard).
#
# bin/audit.sh is GENERATED by a `cat > "$AI_STACK/bin/audit.sh" <<'EOF' … EOF`
# heredoc in installer/phases/04g_security.sh. The two must stay byte-identical — a
# fix applied to one but not the other silently ships a stale security smoke test
# (and `install 04g` would later clobber a hand-edit to bin/audit.sh). This check
# extracts the heredoc body and diffs it against the committed bin/audit.sh. The
# heredoc is single-quoted ('EOF') so its body is literal (no var expansion) and
# must equal bin/audit.sh exactly. Pure file comparison; no external calls.
CHECKS+=(audit_drift)
CHECK_TITLE[audit_drift]="bin/audit.sh in sync with its 04g generator heredoc"

audit_drift_diagnose() {
  local gen="$AI_STACK/installer/phases/04g_security.sh" out="$AI_STACK/bin/audit.sh"
  [[ -f "$gen" && -f "$out" ]] || { echo "04g_security.sh or bin/audit.sh missing — cannot compare. [skip]"; return 0; }
  local exp
  exp="$(awk "/^cat > .*bin\/audit.sh.* <<'EOF'/{f=1;next} f&&/^EOF\$/{f=0} f" "$gen")"
  if [[ -z "$exp" ]]; then
    echo "could not locate the bin/audit.sh heredoc in 04g_security.sh (generator changed shape — update this check)."
    return 1
  fi
  if [[ "$exp" != "$(cat "$out")" ]]; then
    echo "bin/audit.sh DRIFTED from its 04g_security.sh generator heredoc — they must be byte-identical."
    return 1
  fi
  echo "  (bin/audit.sh matches its 04g generator heredoc — $(printf '%s\n' "$exp" | grep -c '') lines)"
  return 0
}

audit_drift_fix() {
  warn "bin/audit.sh and the 04g_security.sh heredoc diverged. Apply the intended change to BOTH"
  warn "  (they must be byte-identical), or re-run 'vz-ai-stack.sh install 04g' to regenerate"
  warn "  bin/audit.sh from the 04g heredoc (this DISCARDS any hand-edit to bin/audit.sh)."
  return 1
}
