# Rendered runtime artifacts reference only models LiteLLM can actually route.
#
# Several OPT-IN phases render WRITE-ONCE runtime artifacts that BAKE a model NAME
# at install time. A version-less catalog cutover (`model sync` / a models.yml
# add·remove·rename) re-registers litellm/config.yaml's routable model_list but does
# NOT re-seed these artifacts, so a stale baked name 400s at completion while the
# venv/daemon/key still look healthy — a class of drift doctor did not watch before
# (these consumers are the opt-in fleet NOT covered by `model sync`'s key widening).
#
# Validates (READ-ONLY: file parse + yq only — NO inference, NO scoped-key calls,
# OOM-safe by construction) that every model a rendered artifact references is a
# routable `model_name` in litellm/config.yaml's model_list:
#   (i)  bin/{metagpt,oasis,agentscope,concordia} — baked default `${<APP>_MODEL:-<name>}`.
#   (ii) deer-flow/config.yaml — every picker entry's `model:` (Phase 10).
# (~/.openwork-stack/opencode.json's model set is guarded by phase-29's content-aware
#  precheck + the reconcile regression test's denylist — not duplicated here.)
#
# Routable set = the ON-DISK model_list (NOT any scoped key's /v1/models, which can
# still list stale aliases that 400) — the same source check 51 validates against.
#
# Conditional: each artifact is validated ONLY when present (opt-in) — a missing one
# is a clean skip, never a failure. WARN-skips the whole check when yq or the LiteLLM
# config is absent (can't derive the routable set).
CHECKS+=(rendered_artifact_routability)
CHECK_TITLE[rendered_artifact_routability]="Rendered artifacts (bin wrappers · deerflow picker) route to real LiteLLM models"

rendered_artifact_routability_diagnose() {
  local cfg="$AI_STACK/litellm/config.yaml"
  if ! command -v yq >/dev/null 2>&1; then
    echo "yq not installed — cannot derive LiteLLM's routable model_list to validate rendered artifacts (skipping)"
    return 0
  fi
  [[ -f "$cfg" ]] || { echo "litellm/config.yaml missing ($cfg) — cannot derive the routable set (skipping)"; return 0; }
  local routable
  routable="$(yq -r '.model_list[].model_name' "$cfg" 2>/dev/null | sed '/^$/d;/^null$/d')"
  [[ -n "$routable" ]] || { echo "litellm/config.yaml lists no model_name in model_list — cannot validate (skipping)"; return 0; }

  local fail=0

  # (i) bin/{metagpt,agentscope,oasis}: baked default `${<ENV>_MODEL:-<name>}`.
  # pair = <wrapper-basename>:<env-var>:<phase>.
  local pair app evar phase w def
  for pair in "metagpt:METAGPT_MODEL:32" "agentscope:AGENTSCOPE_MODEL:33" "oasis:OASIS_MODEL:34" "concordia:CONCORDIA_MODEL:37"; do
    app="${pair%%:*}"; evar="${pair#*:}"; phase="${evar##*:}"; evar="${evar%%:*}"
    w="$AI_STACK/bin/$app"
    [[ -f "$w" ]] || continue
    # Extract the literal between ':-' and the closing '}' (parameter-expansion default).
    def="$(grep -oE "${evar}:-[^}]+}" "$w" 2>/dev/null | head -1)"
    def="${def#*:-}"; def="${def%\}}"
    [[ -n "$def" ]] || continue    # couldn't parse a baked default — never false-fail
    if ! printf '%s\n' "$routable" | grep -qxF "$def"; then
      echo "bin/$app baked default model '$def' is NOT a routable LiteLLM model_name — re-render: 'rm $AI_STACK/installer/state/phase_${phase}*.done' + 'vz-ai-stack.sh install ${phase}'"
      fail=1
    fi
  done

  # (ii) deer-flow/config.yaml: picker entries' `model:` (Phase 10; regenerated by `model sync`).
  local df="$AI_STACK/deer-flow/config.yaml" m
  if [[ -f "$df" ]]; then
    local df_stale=()
    while IFS= read -r m; do
      [[ -n "$m" && "$m" != "null" ]] || continue
      printf '%s\n' "$routable" | grep -qxF "$m" || df_stale+=("$m")
    done < <(yq -r '.models[].model' "$df" 2>/dev/null)
    if (( ${#df_stale[@]} > 0 )); then
      echo "deer-flow/config.yaml picker model(s) not routable in LiteLLM config: ${df_stale[*]} — regenerate the picker: 'vz-ai-stack.sh model sync' (or 'vz-ai-stack.sh install 10')"
      fail=1
    fi
  fi

  return $fail
}

rendered_artifact_routability_fix() {
  warn "A rendered artifact bakes a model name LiteLLM can no longer route (catalog drift after a"
  warn "version-less add/remove/rename). These artifacts are write-once and are NOT re-seeded by"
  warn "'model sync', so re-render the SPECIFIC one named in the failure detail above:"
  warn "  bin/metagpt|agentscope|oasis : rm the matching installer/state/phase_3X*.done, then 'vz-ai-stack.sh install 3X'"
  warn "  deer-flow/config.yaml picker : 'vz-ai-stack.sh model sync' (regenerates the picker from served models)"
  return 1
}
