# bin/halo in sync with its 11_halo_autoreason.sh generator (default-model drift guard).
#
# bin/halo is GENERATED by a `cat > "$HALO_WRAPPER" <<WRAPEOF … WRAPEOF` heredoc in
# installer/phases/11_halo_autoreason.sh (:89), and the ONLY value that varies is the
# default model — HALO_MODEL_DEFAULT (:22), emitted into the wrapper's exec line (:118) as
#   exec "$HALO_BIN" --model "${HALO_MODEL:-<HALO_MODEL_DEFAULT>}" "$@"
# Because bin/halo is ALSO git-tracked, a change to HALO_MODEL_DEFAULT that isn't re-committed
# leaves the committed wrapper stale, so EVERY `install` (which re-runs phase 11) regenerates
# bin/halo and dirties the tree with pure noise. That is exactly how the committed default
# went stale at `local` while the generator moved to `claude-opus-sub-xhigh` (2026-07-17 fix).
#
# UNLIKE check 62 (bin/audit.sh) this is NOT a byte-diff of the heredoc body: phase 11's
# heredoc is UNQUOTED (`<<WRAPEOF`, not `<<'EOF'`), so `${HALO_MODEL_DEFAULT}`/`$AI_STACK`/… are
# EXPANDED at generation — a literal extract would never match the committed expanded wrapper.
# We instead assert only the one field that actually drifts (the default model), with ZERO
# eval: read HALO_MODEL_DEFAULT from the phase, then assert the committed bin/halo carries the
# matching `${HALO_MODEL:-<value>}` default. Pure file reads; no external calls, no heredoc exec.
CHECKS+=(halo_drift)
CHECK_TITLE[halo_drift]="bin/halo default model in sync with its 11_halo_autoreason.sh generator"

halo_drift_diagnose() {
  local gen="$AI_STACK/installer/phases/11_halo_autoreason.sh" out="$AI_STACK/bin/halo"
  [[ -f "$gen" && -f "$out" ]] || { echo "11_halo_autoreason.sh or bin/halo missing — cannot compare. [skip]"; return 0; }

  # HALO_MODEL_DEFAULT="…"  (first assignment in the generator). Strip quotes.
  local want
  want="$(grep -m1 -E '^[[:space:]]*HALO_MODEL_DEFAULT=' "$gen" | sed -E 's/^[^=]*=//; s/[[:space:]]*#.*//; s/^"//; s/"[[:space:]]*$//; s/^'\''//; s/'\''[[:space:]]*$//')"
  if [[ -z "$want" ]]; then
    echo "could not read HALO_MODEL_DEFAULT from 11_halo_autoreason.sh (generator changed shape — update this check)."
    return 1
  fi

  # The committed wrapper must carry the SAME default: ${HALO_MODEL:-<want>}
  if ! grep -qF "\${HALO_MODEL:-${want}}" "$out"; then
    local have
    have="$(grep -oE '\$\{HALO_MODEL:-[^}]*\}' "$out" | head -1)"
    echo "bin/halo DRIFTED from its 11_halo_autoreason.sh generator: generator default is"
    echo "  '${want}' but committed bin/halo has '${have:-no \${HALO_MODEL:-…} default found}'."
    echo "  Every 'install' regenerates bin/halo → this dirties git with pure noise."
    return 1
  fi
  echo "  (bin/halo default model matches the generator: \${HALO_MODEL:-${want}})"
  return 0
}

halo_drift_fix() {
  warn "bin/halo's default model diverged from HALO_MODEL_DEFAULT in 11_halo_autoreason.sh."
  warn "  Re-sync + commit bin/halo:  mayssam-ai-stack.sh install 11   (regenerates bin/halo), then"
  warn "  'git add bin/halo && git commit' so the tracked wrapper matches the generator again."
  return 1
}
