#!/usr/bin/env bash
# Phase 03 — Honcho self-hosted (cross-agent memory).
#
# Clones plastic-labs/honcho into ~/ai-stack/honcho, configures it to talk to
# LiteLLM for embeddings/LLM calls (so cost is observable in Phoenix), points
# Postgres data into ~/ai-stack/data/honcho, and brings the stack up.
#
# Conservative-recreate: if honcho/ already has a non-empty checkout and the
# compose stack is running, we treat it as managed and only patch .env on drift.
set -Eeuo pipefail
AI_STACK="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$AI_STACK/installer/lib/common.sh"
source "$AI_STACK/installer/lib/env.sh"
source "$AI_STACK/installer/lib/docker.sh"
source "$AI_STACK/installer/lib/validate.sh"

PHASE=03
HONCHO_DIR="$AI_STACK/honcho"

precheck() {
  [[ -d "$HONCHO_DIR/.git" ]] || return 1
  [[ -f "$HONCHO_DIR/docker-compose.yml" ]] || return 1
  [[ -f "$HONCHO_DIR/docker-compose.override.yml" ]] || return 1
  [[ -f "$HONCHO_DIR/.env" ]] || return 1
  # Try alias first (post-refactor), then loopback fallback.
  local hb; hb="${HONCHO_BASE_URL:-$(get_env HONCHO_BASE_URL http://honcho:8000)}"
  wait_http "${hb}/health" 5 || wait_http http://127.0.10.6:8000/health 5 || return 1
  [[ -n "$(get_env HONCHO_API_KEY "")" ]] || return 1
  return 0
}

if precheck 2>/dev/null && stamp_check "$PHASE"; then
  ok "phase $PHASE already complete (honcho)"
  exit 0
fi

hdr "Phase 03 — Honcho (memory)"

# --- Clone (or update) ---
if [[ ! -d "$HONCHO_DIR/.git" ]]; then
  log "Cloning Honcho into a .partial dir (atomic on success)..."
  rm -rf "${HONCHO_DIR}.partial"
  if ! git clone https://github.com/plastic-labs/honcho "${HONCHO_DIR}.partial"; then
    err "git clone failed; cleaning ${HONCHO_DIR}.partial"
    rm -rf "${HONCHO_DIR}.partial"
    exit 1
  fi
  # If the empty dir existed (from Phase 00 mkdir), move .partial into place.
  rmdir "$HONCHO_DIR" 2>/dev/null || true
  mv "${HONCHO_DIR}.partial" "$HONCHO_DIR"
  ok "cloned to $HONCHO_DIR"
else
  log "Honcho repo already present; skipping clone."
fi

# --- Copy templates ---
cd "$HONCHO_DIR"
if [[ ! -f docker-compose.yml ]]; then
  if [[ -f docker-compose.yml.example ]]; then
    cp docker-compose.yml.example docker-compose.yml
    ok "wrote docker-compose.yml from example"
  else
    err "honcho/docker-compose.yml.example missing — upstream layout may have changed."
    err "Inspect $HONCHO_DIR and adjust phase 03 accordingly."
    exit 1
  fi
fi
if [[ ! -f .env ]]; then
  if [[ -f .env.template ]]; then
    cp .env.template .env
    ok "wrote $HONCHO_DIR/.env from template"
  fi
fi

# --- Override: persistent volume + ai-stack network membership + alias publish ---
# Compose does NOT expand ~ — use absolute $HOME.
# Honcho's redis defaults to 127.0.0.1:6379 which collides with FalkorDB.
# Remove the host port publish entirely — honcho's api/deriver still reach
# redis over the internal docker network at hostname `redis:6379`.
# api + deriver join the external ai-stack bridge network so they can dial
# litellm/qdrant via Docker DNS. api binds host alias `honcho`
# (127.0.10.6:8000 → :8000).
cat > "$HONCHO_DIR/docker-compose.override.yml" <<EOF
# Auto-generated by installer phase 03. Edit with care.
# Networking (post-refactor): api + deriver join the external ai-stack bridge
# network so they can dial litellm/qdrant/phoenix via the alias scheme. The
# api binds the host alias \`honcho\` (127.0.10.6:8000 → :8000). redis and
# database stay on the default network only (no cross-stack reachability
# needed). Cross-stack calls from api/deriver use fully-qualified DNS
# (litellm.ai-stack:4000) — see D28 in refactor-design-final.md.
services:
  database:
    volumes:
      - type: bind
        source: $AI_STACK/data/honcho
        target: /var/lib/postgresql/data
  redis:
    # Override upstream's '127.0.0.1:6379:6379' to avoid clash with FalkorDB.
    # Internal docker network access via 'redis:6379' is unaffected.
    ports: !reset []
  api:
    networks: [default, ai-stack]
    ports:
      - "127.0.10.6:8000:8000"
  deriver:
    networks: [default, ai-stack]
networks:
  ai-stack:
    external: true
EOF
ok "wrote docker-compose.override.yml"

# --- Patch honcho/.env to point LLM/embeddings at LiteLLM (so Phoenix sees it) ---
# Honcho reads OpenAI-compatible env vars for its 'openai' provider.
# NOTE (council): this section runs on a FRESH install (the precheck above fails →
# full run). On an ALREADY-RUNNING stack the precheck short-circuits, AND a plain
# `docker compose restart` does NOT reload env_file — so to apply an env change to
# a live stack you must clear the stamp and/or run
# `docker compose up -d --force-recreate api deriver` after editing honcho/.env.
LITELLM_KEY="$(get_env LITELLM_MASTER_KEY "")"
[[ -n "$LITELLM_KEY" ]] || { err "LITELLM_MASTER_KEY empty; run phase 00 first"; exit 1; }

# Idempotent upsert helpers for honcho's own .env
honcho_set_env() {
  local key="$1" val="$2" envf="$HONCHO_DIR/.env"
  local tmp; tmp="$(mktemp "${envf}.XXXXXX")"
  awk -v k="$key" -v v="$val" '
    BEGIN { found=0 }
    /^[[:space:]]*#/ { print; next }
    { n = index($0, "="); if (n>0) { lk=substr($0,1,n-1); if (lk==k) { if (!found) { print k"="v; found=1 } next } } print }
    END { if (!found) print k"="v }
  ' "$envf" > "$tmp" && mv -f "$tmp" "$envf"
}
# Remove a key entirely, so honcho/.env never carries a stale/legacy var
# (e.g. the pre-v3 LLM_OPENAI_API_BASE / LLM_OPENAI_MODEL names).
honcho_unset_env() {
  local key="$1" envf="$HONCHO_DIR/.env"
  [[ -f "$envf" ]] || return 0
  local tmp; tmp="$(mktemp "${envf}.XXXXXX")"
  awk -v k="$key" '
    /^[[:space:]]*#/ { print; next }
    { n = index($0, "="); if (n>0 && substr($0,1,n-1)==k) next; print }
  ' "$envf" > "$tmp" && mv -f "$tmp" "$envf"
}
honcho_set_env LLM_OPENAI_API_KEY  "$LITELLM_KEY"
# Global OpenAI-compatible base URL for ALL openai-transport roles (deriver,
# dialectic, summary, dream). Honcho v3 reads LLM_OPENAI_BASE_URL — the older
# LLM_OPENAI_API_BASE name is silently dropped (pydantic extra="ignore"), which
# left base_url unset → every chat/dialectic call hit api.openai.com and 401'd
# with the local key. Fully-qualified Docker DNS (litellm.ai-stack:4000) —
# required because honcho-api joins BOTH the default and ai-stack networks; bare
# `litellm` could collide with a name on the default network. Per D28.
honcho_set_env LLM_OPENAI_BASE_URL "http://litellm.ai-stack:4000/v1"
# Purge the legacy/ignored pre-v3 keys so honcho/.env never shows a stale base
# or a stale (local-gemma4) model.
honcho_unset_env LLM_OPENAI_API_BASE
honcho_unset_env LLM_OPENAI_MODEL
# Platform model policy: every text-generation role (deriver, all 5 dialectic
# reasoning levels, summary, both dream specialists) uses the platform default
# claude-opus-sub-xhigh (Claude subscription via Meridian). transport stays
# the default "openai", so calls route through LiteLLM via LLM_OPENAI_BASE_URL
# above; LiteLLM falls back to local-gemma4 only if Meridian is down. Embeddings
# stay on text-embedding-3-small (not a chat model). Override per-deploy with
# HONCHO_MODEL in the stack .env.
HONCHO_MODEL="$(get_env HONCHO_MODEL "claude-opus-sub-xhigh")"
for _hk in \
  DERIVER_MODEL_CONFIG__MODEL \
  DIALECTIC_LEVELS__minimal__MODEL_CONFIG__MODEL \
  DIALECTIC_LEVELS__low__MODEL_CONFIG__MODEL \
  DIALECTIC_LEVELS__medium__MODEL_CONFIG__MODEL \
  DIALECTIC_LEVELS__high__MODEL_CONFIG__MODEL \
  DIALECTIC_LEVELS__max__MODEL_CONFIG__MODEL \
  SUMMARY_MODEL_CONFIG__MODEL \
  DREAM_DEDUCTION_MODEL_CONFIG__MODEL \
  DREAM_INDUCTION_MODEL_CONFIG__MODEL; do
  honcho_set_env "$_hk" "$HONCHO_MODEL"
done
honcho_set_env AUTH_USE_AUTH       "false"
ok "patched $HONCHO_DIR/.env to use LiteLLM"

# --- Compose up ---
if ! container_running honcho-api 2>/dev/null && ! container_running honcho 2>/dev/null; then
  log "Bringing Honcho up via docker compose..."
  (cd "$HONCHO_DIR" && docker compose up -d 2>&1 | tail -10)
fi
HONCHO_SMOKE="${HONCHO_BASE_URL:-$(get_env HONCHO_BASE_URL http://honcho:8000)}"
wait_http "${HONCHO_SMOKE}/health" 120 \
  || wait_http http://127.0.10.6:8000/health 120 \
  || { err "Honcho /health didn't come up"; exit 1; }
ok "Honcho /health responds"

# --- Persist HONCHO_API_KEY into stack .env ---
if [[ -z "$(get_env HONCHO_API_KEY "")" ]]; then
  set_env HONCHO_API_KEY "honcho-local-$(openssl rand -hex 24)"
  warn "Generated HONCHO_API_KEY. LiteLLM may need restart if it consumes this var."
  queue_restart litellm
fi

stamp_mark "$PHASE"
record "phase 03 complete: honcho up at http://honcho:8000 (127.0.10.6:80)"
ok "Phase 03 — Honcho — complete"
