#!/usr/bin/env bash
# Phase 07 — AutoFyn (second agent type, own sandbox).
set -Eeuo pipefail
AI_STACK="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$AI_STACK/installer/lib/common.sh"
source "$AI_STACK/installer/lib/env.sh"
source "$AI_STACK/installer/lib/validate.sh"

PHASE=07
AF_DIR="$AI_STACK/autofyn"

precheck() {
  [[ -d "$AF_DIR/.git" || -f "$AF_DIR/docker-compose.yml" ]] || return 1
  # If compose present and running, healthcheck.
  if [[ -f "$AF_DIR/docker-compose.yml" ]]; then
    (cd "$AF_DIR" && docker compose ps 2>/dev/null | grep -q running) || return 1
  fi
  return 0
}

if precheck 2>/dev/null && stamp_check "$PHASE"; then
  ok "phase $PHASE already complete (autofyn)"
  exit 0
fi

hdr "Phase 07 — AutoFyn"

if [[ ! -d "$AF_DIR/.git" && ! -f "$AF_DIR/docker-compose.yml" ]]; then
  log "Cloning AutoFyn (best effort)..."
  rm -rf "${AF_DIR}.partial"
  if git clone https://github.com/SignalPilot-Labs/AutoFyn "${AF_DIR}.partial" 2>&1 | tail -5; then
    rmdir "$AF_DIR" 2>/dev/null || true
    mv "${AF_DIR}.partial" "$AF_DIR"
    ok "cloned to $AF_DIR"
  else
    rm -rf "${AF_DIR}.partial"
    warn "AutoFyn clone failed (upstream URL may differ). Place source at $AF_DIR and re-run."
    stamp_mark "$PHASE"
    ok "Phase 07 — AutoFyn — stub complete (upstream-unreachable; manual setup)"
    exit 0
  fi
fi

if [[ -f "$AF_DIR/docker-compose.yml" ]]; then
  # AutoFyn's compose needs ~10 env vars (AGENT_INTERNAL_SECRET,
  # SANDBOX_INTERNAL_SECRET, AF_IMAGE_TAG, HOST_IP, AF_SANDBOX_PORT, …).
  # The upstream's autofyn CLI generates these via openssl + ipconfig; we
  # replicate that into a .env file in the repo so `docker compose up -d`
  # reads them via env_file: ./.env (compose's default).
  if [[ ! -f "$AF_DIR/.env" ]]; then
    log "Generating $AF_DIR/.env with random secrets + safe defaults..."
    host_ip="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "")"
    # Create file with 0600 from the start to avoid the umask race
    # (heredoc into a fresh file uses the user's umask, which is often
    # 0022 → 0644). Touch+chmod first, then write.
    install -m 600 /dev/null "$AF_DIR/.env"
    cat > "$AF_DIR/.env" <<EOF
# Auto-generated by ai-stack/installer/phases/07_autofyn.sh
# Replicates upstream autofyn CLI's secret + tag generation
# (cli/scripts/start.sh).
AGENT_INTERNAL_SECRET=$(openssl rand -hex 32)
SANDBOX_INTERNAL_SECRET=$(openssl rand -hex 32)
CONNECTOR_SECRET=$(openssl rand -hex 32)
AF_IMAGE_TAG=stable
AF_SANDBOX_PORT=8923
# AGENT_PORT intentionally omitted: the agent app binds 0.0.0.0:8500
# inside the container regardless of env. The compose healthcheck targets
# ${AGENT_PORT:-8500} — leaving it unset makes it default to 8500, which
# matches the actual listener. Setting AGENT_PORT to anything else (like
# the previous 3402) made the healthcheck target a closed port and the
# agent showed as unhealthy forever.
CONNECTOR_PORT=3403
AF_ALLOW_DOCKER=true
HOST_IP=${host_ip}
# DB_PASSWORD is intentionally STABLE (matches the upstream compose default).
# Rotating it would orphan the postgres data volume — the volume keeps the
# old password hash from initdb, so a new password causes auth failures.
# To rotate safely: stop containers, `docker volume rm autofyn_autofyn-db`,
# update password, then re-up.
DB_PASSWORD=autofyn
POSTGRES_VERSION=16
EOF
    # install -m 600 above set the perms; verify
    chmod 600 "$AF_DIR/.env"
    ok "wrote $AF_DIR/.env (chmod 600; random DB_PASSWORD generated)"
  fi
  (cd "$AF_DIR" && docker compose up -d 2>&1 | tail -10) || warn "compose up exited non-zero — image pull may have failed (try 'docker compose -f $AF_DIR/docker-compose.yml logs')"
  wait_http http://autofyn:3400 90 || warn "autofyn UI didn't respond on :3400 — first-pull / build can take several minutes"
fi

stamp_mark "$PHASE"
record "phase 07 complete: autofyn $([[ -f $AF_DIR/docker-compose.yml ]] && echo up || echo not-configured)"
ok "Phase 07 — AutoFyn — complete"
